INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GPIOD "libzmq")

FIND_PATH(GPIOD_INCLUDE_DIRS
    NAMES gpiod.h
    HINTS ${PC_GPIOD_INCLUDE_DIR}
    ${CMAKE_INSTALL_PREFIX}/include
    PATHS
    /usr/local/include
    /usr/include
)

FIND_LIBRARY(GPIOD_LIBRARIES
    NAMES gpiod libgpiod
    HINTS ${PC_GPIOD_LIBDIR}
    ${CMAKE_INSTALL_PREFIX}/lib
    ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS
    ${GPIOD_INCLUDE_DIRS}/../lib
    /usr/local/lib
    /usr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GPIOD DEFAULT_MSG GPIOD_LIBRARIES GPIOD_INCLUDE_DIRS)
MARK_AS_ADVANCED(GPIOD_LIBRARIES GPIOD_INCLUDE_DIRS)
